# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\email_recovery_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmailRecoveryWindow(object):
    def setupUi(self, EmailRecoveryWindow):
        EmailRecoveryWindow.setObjectName("EmailRecoveryWindow")
        EmailRecoveryWindow.resize(480, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EmailRecoveryWindow.sizePolicy().hasHeightForWidth())
        EmailRecoveryWindow.setSizePolicy(sizePolicy)
        EmailRecoveryWindow.setWindowOpacity(1.0)
        EmailRecoveryWindow.setStyleSheet("* {\n"
"    background-color: #ffffff;\n"
"    font-style: \"Segoe UI\";\n"
"     color: #0B090A;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #0B090A;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #DFE0E2;\n"
"    padding-left: 15px;\n"
"    border-radius: 18px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #fbba72;\n"
"    border: 2px;\n"
"    border-radius: 18px;\n"
"    font-size: 14px;\n"
"    font-weight: regular;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #399918;\n"
"    color: #EEEEEE\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6703c5;\n"
"    color: #EEEEEE;\n"
"}\n"
"")
        self.email_field = QtWidgets.QLineEdit(EmailRecoveryWindow)
        self.email_field.setGeometry(QtCore.QRect(100, 180, 301, 41))
        self.email_field.setMinimumSize(QtCore.QSize(301, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.email_field.setFont(font)
        self.email_field.setFocusPolicy(QtCore.Qt.NoFocus)
        self.email_field.setInputMask("")
        self.email_field.setText("")
        self.email_field.setMaxLength(32767)
        self.email_field.setClearButtonEnabled(True)
        self.email_field.setObjectName("email_field")
        self.email_label = QtWidgets.QLabel(EmailRecoveryWindow)
        self.email_label.setGeometry(QtCore.QRect(110, 150, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("QLabel {\n"
"    color: #0B090A;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    font-style: \"Segoe UI\";\n"
"}")
        self.email_label.setObjectName("email_label")
        self.btn_send_email = QtWidgets.QPushButton(EmailRecoveryWindow)
        self.btn_send_email.setGeometry(QtCore.QRect(130, 290, 101, 41))
        self.btn_send_email.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_send_email.setFont(font)
        self.btn_send_email.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/enviar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_send_email.setIcon(icon)
        self.btn_send_email.setIconSize(QtCore.QSize(24, 24))
        self.btn_send_email.setObjectName("btn_send_email")
        self.btn_close = QtWidgets.QPushButton(EmailRecoveryWindow)
        self.btn_close.setGeometry(QtCore.QRect(260, 290, 101, 41))
        self.btn_close.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton:hover {\n"
"    background-color: #d60000;\n"
"    color: #EEEEEE\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/excluir (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setIconSize(QtCore.QSize(24, 24))
        self.btn_close.setObjectName("btn_close")
        self.window_title_bar = QtWidgets.QWidget(EmailRecoveryWindow)
        self.window_title_bar.setGeometry(QtCore.QRect(0, 0, 481, 51))
        self.window_title_bar.setStyleSheet("* {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(102, 7, 8, 255), stop:1 rgba(102, 7, 8, 255));\n"
"}")
        self.window_title_bar.setObjectName("window_title_bar")
        self.window_title_label = QtWidgets.QLabel(self.window_title_bar)
        self.window_title_label.setGeometry(QtCore.QRect(120, 0, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.window_title_label.setFont(font)
        self.window_title_label.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #EEEEEE;\n"
"    font-size: 22px;\n"
"    font-weight: regular;\n"
"}")
        self.window_title_label.setObjectName("window_title_label")

        self.retranslateUi(EmailRecoveryWindow)
        QtCore.QMetaObject.connectSlotsByName(EmailRecoveryWindow)

    def retranslateUi(self, EmailRecoveryWindow):
        _translate = QtCore.QCoreApplication.translate
        EmailRecoveryWindow.setWindowTitle(_translate("EmailRecoveryWindow", "Eureka®"))
        self.email_label.setText(_translate("EmailRecoveryWindow", "Digite o seu e-mail:"))
        self.btn_send_email.setText(_translate("EmailRecoveryWindow", "Enviar"))
        self.btn_close.setText(_translate("EmailRecoveryWindow", "Cancelar"))
        self.window_title_label.setText(_translate("EmailRecoveryWindow", "Recuperação de senha"))
import resource_rc
