# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\password_change_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 400)
        Dialog.setStyleSheet("* {\n"
"    background-color: #ffffff;\n"
"    font-style: \"Segoe UI\";\n"
"     color: #0B090A;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #0B090A;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #DFE0E2;\n"
"    padding-left: 15px;\n"
"    border-radius: 18px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #fbba72;\n"
"    border: 2px;\n"
"    border-radius: 18px;\n"
"    font-size: 14px;\n"
"    font-weight: regular;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #399918;\n"
"    color: #EEEEEE\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6703c5;\n"
"    color: #EEEEEE;\n"
"}\n"
"")
        self.email_label = QtWidgets.QLabel(Dialog)
        self.email_label.setGeometry(QtCore.QRect(90, 90, 341, 21))
        self.email_label.setObjectName("email_label")
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setGeometry(QtCore.QRect(150, 280, 161, 41))
        self.btn_save.setMinimumSize(QtCore.QSize(0, 41))
        self.btn_save.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/caixa-de-senha-com-asteriscos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon)
        self.btn_save.setIconSize(QtCore.QSize(36, 36))
        self.btn_save.setObjectName("btn_save")
        self.btn_close = QtWidgets.QPushButton(Dialog)
        self.btn_close.setGeometry(QtCore.QRect(180, 340, 111, 41))
        self.btn_close.setMinimumSize(QtCore.QSize(0, 41))
        self.btn_close.setStyleSheet("QPushButton:hover {\n"
"    background-color: #d60000;\n"
"    color: #EEEEEE\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/excluir (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setIconSize(QtCore.QSize(24, 24))
        self.btn_close.setObjectName("btn_close")
        self.window_title_bar = QtWidgets.QWidget(Dialog)
        self.window_title_bar.setGeometry(QtCore.QRect(0, 0, 481, 51))
        self.window_title_bar.setStyleSheet("* {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(102, 7, 8, 255), stop:1 rgba(102, 7, 8, 255));\n"
"}")
        self.window_title_bar.setObjectName("window_title_bar")
        self.label_2 = QtWidgets.QLabel(self.window_title_bar)
        self.label_2.setGeometry(QtCore.QRect(90, 0, 321, 51))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #EEEEEE;\n"
"    font-size: 22px;\n"
"    font-weight: regular;\n"
"    font-style: \"Segoe UI\";\n"
"}")
        self.label_2.setObjectName("label_2")
        self.email_label_2 = QtWidgets.QLabel(Dialog)
        self.email_label_2.setGeometry(QtCore.QRect(90, 180, 341, 21))
        self.email_label_2.setObjectName("email_label_2")
        self.password_field = QtWidgets.QLineEdit(Dialog)
        self.password_field.setGeometry(QtCore.QRect(80, 120, 301, 41))
        self.password_field.setMinimumSize(QtCore.QSize(301, 41))
        self.password_field.setInputMask("")
        self.password_field.setText("")
        self.password_field.setMaxLength(10)
        self.password_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field.setClearButtonEnabled(True)
        self.password_field.setObjectName("password_field")
        self.password_field_2 = QtWidgets.QLineEdit(Dialog)
        self.password_field_2.setGeometry(QtCore.QRect(80, 210, 301, 41))
        self.password_field_2.setMinimumSize(QtCore.QSize(301, 41))
        self.password_field_2.setInputMask("")
        self.password_field_2.setText("")
        self.password_field_2.setMaxLength(10)
        self.password_field_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field_2.setClearButtonEnabled(True)
        self.password_field_2.setObjectName("password_field_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.email_label.setText(_translate("Dialog", "Digite a nova senha:"))
        self.btn_save.setText(_translate("Dialog", " Redefinir senha"))
        self.btn_close.setText(_translate("Dialog", " Cancelar"))
        self.label_2.setText(_translate("Dialog", "Redefinir senha"))
        self.email_label_2.setText(_translate("Dialog", "Confirme a nova senha:"))
import resource_rc
